dist: xenial
language: node_js
node_js:
  - 8.11.3
services:
  - docker
script:
  build:
    - npm run build
 - docker build -t mdontsov/frontend .
 - docker login -u=mdontsov -p=123456789
 - docker push mdontsov/frontend
 
# before_install:
#   - docker build -t mdontsov/frontend --file ./Dockerfile .
# install:
#   - npm install
# build:
#   - npm run build
