dist: xenial
language: node_js
node_js:
  - 8.11.3
services:
  - docker
before_install:
  - docker build -t mdontsov/react-redux-registration-login-example .
install:
  - npm install
build:
  - npm run build
script:
  - docker images mdontsov/react-redux-registration-login-example
  
